# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NuzurCli < Formula
  desc "nuzur cli tool"
  homepage "https://nuzur.com/"
  version "1.4.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.4.5/nuzur-cli_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "c1817d3c6c994f77f5f83bb5e17f9e5dd34e34aa3afb9c4fe098c4b8bfcc7039"

      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.4.5/nuzur-cli_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "a76322538178984b0a375be2a26489d5e9f7415b02a717f7d986f3f1bc7b8de5"

      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.4.5/nuzur-cli_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "73766ca1125ac49668a91403bcc3d877ff1cb22c55e4bd712284888df883b952"
      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.4.5/nuzur-cli_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e7639524addb9f7e900bc486fadd3205115364184b3729f8a5fcb29b4cade1e7"
      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
