# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NuzurCli < Formula
  desc "nuzur cli tool"
  homepage "https://nuzur.com/"
  version "1.8.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.8.4/nuzur-cli_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "56885d07eb38a8c594fe8069ae7b21b182b7be1037fb7bb348be7cb10dc8023f"

      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.8.4/nuzur-cli_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "6d1cc2ee1b5052b226a99722a4815411b94e6cfec894839d226929016b243dc7"

      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.8.4/nuzur-cli_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "fd022fba9bb738c60b9befeee6cb933cfd22bc6a29b344a20c514dc851d2e5de"
      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuzur/nuzur-cli/releases/download/v1.8.4/nuzur-cli_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "04810cc8c6a15f36950f190d78f87a29ab482d55adc793adc10e3ae4db5aae17"
      define_method(:install) do
        bin.install "nuzur-cli"
        bin.install_symlink bin/"nuzur-cli" => "nuzur"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
